# Generated by Django 4.1.7 on 2023-04-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                help_text="Введите название ингридиента.",
                max_length=200,
                verbose_name="Название",
            ),
        ),
    ]
